version: '3.8'

services:
  web:
    build: .
    container_name: panel_web
    restart: always
    ports:
      - "5000:5000"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - .:/app
      - /var/run/docker.sock:/var/run/docker.sock
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:15-alpine
    container_name: panel_db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin_pass
      POSTGRES_DB: panel_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # ДОДАЄМО СЕРВІС МОНІТОРИНГУ
  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.47.0 # Стабільна версія
    container_name: cadvisor
    restart: always
    ports:
      - "8080:8080" # Порт для доступу до метрик
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro

  caddy:
    image: caddy:2.7
    container_name: panel_proxy
    restart: always
    ports:
      - "80:80"    
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - web

volumes:
  postgres_data:
  caddy_data:
  caddy_config: